In [1]:
import pandas as pd
import numpy as np
import warnings
import time
from datetime import datetime, timedelta, date
warnings.filterwarnings('ignore')
import os
pd.options.display.max_columns = 500
pd.options.display.max_rows = 500
from dateutil.relativedelta import relativedelta
from numpy import concatenate as cct
import glob

In [2]:
import openpyxl

In [3]:
path = os.getcwd()

In [4]:
path

'C:\\Users\\Tithi Hunka\\OneDrive - Pine Labs Private Limited\\TermLoans Code_Dummy'

In [5]:
df_lendingkart = pd.read_csv(path+'\\LK\\LK.csv')

In [6]:
df_lendingkart.head()

,application_id,leadid,cls_app_id,email_id,mobile_number,created_by,SubDSA Details,customer_name,unique_id,app_created_date,app_modified_date,lead_source,created_by.1,company_name,regitration_type,industry,pincode,city,state,revenuerange,age_of_business,delivery_method,application_type,product_type,desired_amount,cibil_status,Status,Substatus,Rejection_reason,terms_sent_date,terms_amount,interest_rate,interest_rate_type,terms_tenure,processing_fess,insurer_name,insurance_amount,loan_amount,FI_Status,FI_Substatus,acceptance_status,acceptance_reason,risk_status,agreement_generated_date,agreement_sent_date,agreement_status,agreement_sent_by,courier_company_name,disbursal_date,disbursed_interest_rate,disbursed_amount,disbursed_tenure,first_installment_date
0,LAI-120969985,34792731,LAI-120969985,mdbilalmoujan@gmail.com,8.790301e+09,PineLabs_Direct,NaN,MD BILAL,NaN,15-12-2023,03-01-2024,PineLabs_Direct,PineLabs_Direct,NaN,Proprietorship,Food grains and other related products,NaN,NaN,NaN,12 - 30 Lacs,1 to 5 Years,Regular,New,Term Loan,0,ACCEPTED,Application in Progress,Application Details Incomplete,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,LAI-120307029,33857735,LAI-120307029,gopaljaat061@gmail.com,9.664212e+09,PineLabs_Direct,NaN,gopal singh,NaN,28-10-2023,03-01-2024,PineLabs_Direct,PineLabs_Direct,SHRI KHATU SHYAM BOREWELL COM. AND MATERIAL SU...,Proprietorship,Food grains and other related products,321602.0,BHARATPUR,RAJASTHAN,1 - 10 Crores,1 to 5 Years,Pending,New,Term Loan,0,ACCEPTED,Application Rejected,Reject - Expired,Application Expired-Dedupe,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,LAI-119634947,32847833,LAI-119634947,shreesaipali@gmail.com,9.672816e+09,PineLabs_Direct,NaN,LAXMAN HARIRAM,64fcb82333bdb69a50989e8a,10-09-2023,03-01-2024,PineLabs_Direct,PineLabs_Direct,SHREE SAI INFOTECH,Proprietorship,Computers;Mobile & related Accessories,306401.0,PALI,RAJASTHAN,30 - 60 Lacs,More than 5 Years,Pending,New,Term Loan,500000,ACCEPTED,Application Rejected,Reject - By Customer,Client not responding,11-09-2023,467000.0,1.40,Flat,60.0,22886.6,ICICI-Income Suraksha,22604.0,467000.0,NaN,NaN,Terms Non-Moving,Application Rejected,NaN,NaN,NaN,Application Rejected,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,LAI-121206347,35251695,LAI-121206347,lokeshsharma962@gmail.com,9.654073e+09,PineLabs_Direct,NaN,Somveer Sharma,NaN,03-01-2024,03-01-2024,PineLabs_Direct,PineLabs_Direct,NaN,Proprietorship,NaN,NaN,NaN,NaN,60 Lacs - 1 Crore,1 to 5 Years,Regular,New,Term Loan,0,REJECTED,Application Rejected,Reject - Lead,CIBIL Rejected Due to Low CIBIL Score,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,LAI-120763811,34486031,LAI-120763811,savithrum@gmail.com,8.754343e+09,PineLabs_Direct,NaN,SAVITHRU MUTHU,656a0699af299a8d4ec65b2e,01-12-2023,03-01-2024,PineLabs_Direct,PineLabs_Direct,HOTEL NEW THEVAR AC NON VEG,Partnership,Restaurant & Hospitality,613001.0,THANJAVUR,TAMIL NADU,1 - 10 Crores,More than 5 Years,Regular,New,Term Loan,2000000,ACCEPTED,Disbursed,Disbursed,NaN,11-12-2023,964000.0,1.26,Flat,36.0,38550.0,ICICI-Income Suraksha,28038.0,964000.0,NaN,NaN,Disbursed,NaN,Approved,13-12-2023,19-12-2023,Disbursed,Courier,NaN,03-01-2024,15.12,964000.0,36.0,03-02-2024

In [7]:
df_lendingkart['app_created_date'] = df_lendingkart['app_created_date'].str.slice(6,10)+'-'+df_lendingkart['app_created_date'].str.slice(3,5)+'-'+df_lendingkart['app_created_date'].str.slice(0,2)

In [8]:
df_lendingkart['disbursal_date'] = df_lendingkart['disbursal_date'].str.slice(6,10)+'-'+df_lendingkart['disbursal_date'].str.slice(3,5)+'-'+df_lendingkart['disbursal_date'].str.slice(0,2)

In [9]:
df_lendingkart['app_created_date'].dtype

dtype('O')

In [10]:
df_lendingkart['disbursal_date'].dtype

dtype('O')

In [11]:
df_lendingkart.sample(5)

,application_id,leadid,cls_app_id,email_id,mobile_number,created_by,SubDSA Details,customer_name,unique_id,app_created_date,app_modified_date,lead_source,created_by.1,company_name,regitration_type,industry,pincode,city,state,revenuerange,age_of_business,delivery_method,application_type,product_type,desired_amount,cibil_status,Status,Substatus,Rejection_reason,terms_sent_date,terms_amount,interest_rate,interest_rate_type,terms_tenure,processing_fess,insurer_name,insurance_amount,loan_amount,FI_Status,FI_Substatus,acceptance_status,acceptance_reason,risk_status,agreement_generated_date,agreement_sent_date,agreement_status,agreement_sent_by,courier_company_name,disbursal_date,disbursed_interest_rate,disbursed_amount,disbursed_tenure,first_installment_date
2535,LAI-122050703,36500096,LAI-122050703,avdhootdhamal2212@gmail.com,9.158529e+09,PineLabs_Direct,NaN,Avdhoot Dhamal,65e728807a7cb89ad74dc284,2024-03-05,05-03-2024,PineLabs_Direct,PineLabs_Direct,NaN,Proprietorship,NaN,412802.0,NaN,NaN,1 - 10 Crores,More than 5 Years,Regular,New,Term Loan,1000000,ACCEPTED,Application in Progress,Application Details Incomplete,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
799,LAI-121441814,35601560,LAI-121441814,anasph129@gmail.com,9.745012e+09,PineLabs_Direct,NaN,ANAS P H,NaN,2024-01-20,20-01-2024,PineLabs_Direct,PineLabs_Direct,FAIZ DIGITAL HUB,Proprietorship,Computers;Mobile & related Accessories,673573.0,KOZHIKODE,KERALA,More than 10 Crores,1 to 5 Years,Pending,New,Term Loan,0,ACCEPTED,Application Rejected,Reject - Upfront,Financial Discipline: Decline in Credits/Revenue,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1454,LAI-121589272,35816685,LAI-121589272,raghvedrasingh932@gmail.com,9.691929e+09,PineLabs_Direct,NaN,Raghvendra X,NaN,2024-02-02,06-02-2024,PineLabs_Direct,PineLabs_Direct,ANNU MOBILE SHOP,Proprietorship,Industrial Supplies & Solutions,474005.0,GWALIOR,MADHYA PRADESH,1 - 10 Crores,1 to 5 Years,Pending,New,Term Loan,0,ACCEPTED,Application Rejected,Reject - Lead,Rejected by customer,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
508,LAI-121344736,35457750,LAI-121344736,alokranjansingh002@gmail.com,9.354662e+09,PineLabs_Direct,NaN,Alok Singh,65a109cf961812cef13849f3,2024-01-12,12-01-2024,PineLabs_Direct,PineLabs_Direct,NaN,Proprietorship,NaN,110085.0,NaN,NaN,1 - 10 Crores,More than 5 Years,Regular,New,Term Loan,750000,REJECTED,Application Rejected,Reject - Lead,CIBIL overdue in past loan;CIBIL overdue in cu...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2750,LAI-121477435,35657729,LAI-121477435,bluetickmobile@gmail.com,9.680180e+09,PineLabs_Direct,NaN,Vimla Choudhary,65afedb6cac7c8b7abb004e8,2024-01-23,11-03-2024,PineLabs_Direct,PineLabs_Direct,BLUE TICK MOBILE,Proprietorship,Computers;Mobile & related Accessories,311001.0,BHILWARA,RAJASTHAN,1 - 10 Crores,More than 5 Years,Regular,New,Term Loan,500000,ACCEPTED,Disbursed,Disbursed,NaN,24-01-2024,627000.0,1.31,Flat,36.0,26621.0,NaN,24330.0,627000.0,NaN,NaN,Disbursed,NaN,Approved,05-03-2024,NaN,Disbursed,NaN,NaN,2024-03-11,15.72,627000.0,36.0,05-04-2024

In [12]:
df_lendingkart['Customer ID'] = df_lendingkart['leadid']
df_lendingkart['LAN'] = df_lendingkart['application_id']
df_lendingkart['Contact No.'] = df_lendingkart['mobile_number']
df_lendingkart['Lender Partner '] = 'LendingKart'
df_lendingkart['Merchant Name '] = df_lendingkart['customer_name']
df_lendingkart['Business Name '] = df_lendingkart['company_name']
df_lendingkart['Region'] = ''
df_lendingkart['State'] = df_lendingkart['state']
df_lendingkart['City'] = df_lendingkart['city']
df_lendingkart['Final Lead Status'] = df_lendingkart['Status']
df_lendingkart['Lead Created Date'] = df_lendingkart['app_created_date']
df_lendingkart['Lead last Disposition '] = df_lendingkart['Substatus']
df_lendingkart['Last disposition Date'] = df_lendingkart['app_modified_date']
df_lendingkart['Pendency'] = df_lendingkart['acceptance_status']
df_lendingkart['Monthly turn over of merchant'] = df_lendingkart['revenuerange']
df_lendingkart['Loan Amount Requested'] = df_lendingkart['desired_amount']
df_lendingkart['Sanctioned Amount'] = df_lendingkart['terms_amount']
df_lendingkart['PF Charges'] = df_lendingkart['processing_fess']
df_lendingkart['Doc Charges'] = ''
df_lendingkart['Insurance Charges'] = df_lendingkart['insurance_amount']
df_lendingkart['Net Disbursed Amount'] = df_lendingkart['disbursed_amount']
df_lendingkart['Interest Rate'] = df_lendingkart['interest_rate']
df_lendingkart['Interest Rate Type'] = df_lendingkart['interest_rate_type']
df_lendingkart['Tenure'] = df_lendingkart['terms_tenure']
df_lendingkart['Repayment Frequency'] = ''
df_lendingkart['Approved Date'] = df_lendingkart['terms_sent_date']
df_lendingkart['Disbursed Date'] = df_lendingkart['disbursal_date']
df_lendingkart['Post Sanctioned Status'] = df_lendingkart['acceptance_reason']
df_lendingkart['Rejected Reason'] = df_lendingkart['Rejection_reason']

In [13]:
df_lendingkart.columns

Index(['application_id', 'leadid', 'cls_app_id', 'email_id', 'mobile_number',
       'created_by', 'SubDSA Details', 'customer_name', 'unique_id',
       'app_created_date', 'app_modified_date', 'lead_source', 'created_by.1',
       'company_name', 'regitration_type', 'industry', 'pincode', 'city',
       'state', 'revenuerange', 'age_of_business', 'delivery_method',
       'application_type', 'product_type', 'desired_amount', 'cibil_status',
       'Status', 'Substatus', 'Rejection_reason', 'terms_sent_date',
       'terms_amount', 'interest_rate', 'interest_rate_type', 'terms_tenure',
       'processing_fess', 'insurer_name', 'insurance_amount', 'loan_amount',
       'FI_Status', 'FI_Substatus', 'acceptance_status', 'acceptance_reason',
       'risk_status', 'agreement_generated_date', 'agreement_sent_date',
       'agreement_status', 'agreement_sent_by', 'courier_company_name',
       'disbursal_date', 'disbursed_interest_rate', 'disbursed_amount',
       'disbursed_tenure', 'first_installment_date', 'Customer ID', 'LAN',
       'Contact No.', 'Lender Partner ', 'Merchant Name ', 'Business Name ',
       'Region', 'State', 'City', 'Final Lead Status', 'Lead Created Date',
       'Lead last Disposition ', 'Last disposition Date', 'Pendency',
       'Monthly turn over of merchant', 'Loan Amount Requested',
       'Sanctioned Amount', 'PF Charges', 'Doc Charges', 'Insurance Charges',
       'Net Disbursed Amount', 'Interest Rate', 'Interest Rate Type', 'Tenure',
       'Repayment Frequency', 'Approved Date', 'Disbursed Date',
       'Post Sanctioned Status', 'Rejected Reason'],
      dtype='object')

In [14]:
df_lendingkart.dtypes

application_id                    object
leadid                             int64
cls_app_id                        object
email_id                          object
mobile_number                    float64
created_by                        object
SubDSA Details                   float64
customer_name                     object
unique_id                         object
app_created_date                  object
app_modified_date                 object
lead_source                       object
created_by.1                      object
company_name                      object
regitration_type                  object
industry                          object
pincode                          float64
city                              object
state                             object
revenuerange                      object
age_of_business                   object
delivery_method                   object
application_type                  object
product_type                      object
desired_amount                     int64
cibil_status                      object
Status                            object
Substatus                         object
Rejection_reason                  object
terms_sent_date                   object
terms_amount                     float64
interest_rate                    float64
interest_rate_type                object
terms_tenure                     float64
processing_fess                  float64
insurer_name                      object
insurance_amount                 float64
loan_amount                      float64
FI_Status                         object
FI_Substatus                      object
acceptance_status                 object
acceptance_reason                 object
risk_status                       object
agreement_generated_date          object
agreement_sent_date               object
agreement_status                  object
agreement_sent_by                 object
courier_company_name             float64
disbursal_date                    object
disbursed_interest_rate          float64
disbursed_amount                 float64
disbursed_tenure                 float64
first_installment_date            object
Customer ID                        int64
LAN                               object
Contact No.                      float64
Lender Partner                    object
Merchant Name                     object
Business Name                     object
Region                            object
State                             object
City                              object
Final Lead Status                 object
Lead Created Date                 object
Lead last Disposition             object
Last disposition Date             object
Pendency                          object
Monthly turn over of merchant     object
Loan Amount Requested              int64
Sanctioned Amount                float64
PF Charges                       float64
Doc Charges                       object
Insurance Charges                float64
Net Disbursed Amount             float64
Interest Rate                    float64
Interest Rate Type                object
Tenure                           float64
Repayment Frequency               object
Approved Date                     object
Disbursed Date                    object
Post Sanctioned Status            object
Rejected Reason                   object
dtype: object

In [15]:
df_flexiloansA = pd.read_excel(path+'\\FL\\FL.xlsx',sheet_name='approved',engine='openpyxl')

In [16]:
df_flexiloansA['Customer ID'] = df_flexiloansA['code']
df_flexiloansA['LAN'] = df_flexiloansA['number']
df_flexiloansA['Contact No.'] = df_flexiloansA['Mobile_no']
df_flexiloansA['Lender Partner '] = 'Flexi Loans'
df_flexiloansA['Merchant Name '] = ''
df_flexiloansA['Business Name '] = df_flexiloansA['business_name']
df_flexiloansA['Region'] = ''
df_flexiloansA['State'] = ''
df_flexiloansA['City'] = ''
df_flexiloansA['Final Lead Status'] = df_flexiloansA['s1']
df_flexiloansA['Lead Created Date'] = df_flexiloansA['Created']
df_flexiloansA['Lead last Disposition '] = df_flexiloansA['s3']
df_flexiloansA['Last disposition Date'] = ''
df_flexiloansA['Pendency'] = ''
df_flexiloansA['Monthly turn over of merchant'] = ''
df_flexiloansA['Loan Amount Requested'] = df_flexiloansA['Loan Amount']
df_flexiloansA['Sanctioned Amount'] = df_flexiloansA['Sanctioned Amount']
df_flexiloansA['PF Charges'] = df_flexiloansA['Pf Charges']
df_flexiloansA['Doc Charges'] = df_flexiloansA['Doc Charges']
df_flexiloansA['Insurance Charges'] = ''
df_flexiloansA['Net Disbursed Amount'] = df_flexiloansA['Net Disbursed Amount']
df_flexiloansA['Interest Rate'] = df_flexiloansA['Interest Rate']
df_flexiloansA['Interest Rate Type'] = df_flexiloansA['Interest Rate Type']
df_flexiloansA['Tenure'] = df_flexiloansA['Tenure']
df_flexiloansA['Repayment Frequency'] = df_flexiloansA['Repayment Frequency']
df_flexiloansA['Approved Date'] = df_flexiloansA['Approved Date']
df_flexiloansA['Disbursed Date'] = df_flexiloansA['Disbursed Date']
df_flexiloansA['Post Sanctioned Status'] = ''
df_flexiloansA['Rejected Reason'] = ''

In [17]:
df_flexiloansI = pd.read_excel(path+'\\FL\\FL.xlsx',sheet_name='In_progress',engine='openpyxl')

In [18]:
df_flexiloansI.head()

,code,business_name,application_no,partner_application_number,lead_code,Created,Hot Lead Date,Post_PD_date,offered_amount_pd,Days Since Lead Created,Loan Amount,Total Calls Made,Calls Not Answered,Fresh_Top_Up,s1,s2,s3,Pending Documents,Pending Document Count,Priority,Document_Link,name,platform,MTO,serviceable,Mobile_no,inserted_on
0,65fed6f12rtsm,NEW SHREE RAM ENTERPRISE,PEF-GUFUL-000-MAR24-00012,65fed5d4053024a1a7238a96,5975e584d47d1,2024-03-23,2024-04-01 14:30:14,NaN,NaN,0,1500000,4,1,Fresh,In Progress,Hot Lead,PD,We found the following issue(s) with the banki...,3,1,http://apply.flexiloans.com/?al=true&lm=5975e5...,Pine Labs,Web,1000000.0,1,9376240369,2024-04-01 13:30:17.216
1,65e55eeb51gt0,ROOP JEWELLERS,PEF-KABEN-000-MAR24-00170,65e320768e0e94bb2443918d,65017e751lqc0,2024-03-04,NaT,NaN,NaN,0,1000000,100,96,Fresh,In Progress,Qualified Lead,Form Pending,Documents for 'Bank statement'\nRequired:\nBan...,2,2,http://apply.flexiloans.com/?al=true&lm=65017e...,Pine Labs,Web,400000.0,1,6361038810,2024-04-01 13:30:17.216
2,65d778a4owosn,Mehta Battery,PEF-UTAVA-000-FEB24-00023,65d77811c5917ed766e37566,609129c6jefib,2024-02-22,NaT,NaN,NaN,0,400000,124,121,Fresh,In Progress,Qualified Lead,Form Pending,Documents for 'Residential Address Proof'\nOpt...,4,2,http://apply.flexiloans.com/?al=true&lm=609129...,Pine Labs,Web,1000000.0,1,8127482888,2024-04-01 13:30:17.216
3,65d756f67amhb,Sri Guru Kripa Enterprises,PNF-KABEN-000-FEB24-01883,65216ec70c694df7143afca9,65d756f67k49o,2024-02-22,NaT,NaN,NaN,0,3025000,130,122,Fresh,In Progress,Qualified Lead,Form Pending,Documents for 'KYC'\nRequired:\nPan Card (Fath...,6,2,http://apply.flexiloans.com/?al=true&lm=65d756...,Pine Labs,Web,1000000.0,1,9972032132,2024-04-01 13:30:17.216
4,65e885e1d8zh8,AGRI SCIENCE PRIVATE LIMITED,PNF-MAMUM-000-MAR24-00140,NaN,65e885e1inxg0,2024-03-06,NaT,NaN,NaN,0,60000,22,22,Fresh,In Progress,Qualified Lead,Form Pending,Documents for 'Residential Address Proof'\nOpt...,7,2,http://apply.flexiloans.com/?al=true&lm=65e885...,Pine Labs,Web,200000.0,1,6789987714,2024-04-01 13:30:17.216

In [19]:
df_flexiloansI['Customer ID'] = df_flexiloansI['code']
df_flexiloansI['LAN'] = df_flexiloansI['application_no']
df_flexiloansI['Contact No.'] = df_flexiloansI['Mobile_no']
df_flexiloansI['Lender Partner '] = 'Flexi Loans'
df_flexiloansI['Merchant Name '] = ''
df_flexiloansI['Business Name '] = df_flexiloansI['business_name']
df_flexiloansI['Region'] = ''
df_flexiloansI['State'] = ''
df_flexiloansI['City'] = ''
df_flexiloansI['Final Lead Status'] = df_flexiloansI['s2']
df_flexiloansI['Lead Created Date'] = df_flexiloansI['Created']
df_flexiloansI['Lead last Disposition '] = df_flexiloansI['s3']
df_flexiloansI['Last disposition Date'] = ''
df_flexiloansI['Pendency'] = df_flexiloansI['Pending Documents']
df_flexiloansI['Monthly turn over of merchant'] = ''
df_flexiloansI['Loan Amount Requested'] = df_flexiloansI['Loan Amount']
#df_flexiloansI['Sanctioned Amount'] = ''
df_flexiloansI['Sanctioned Amount'] = np.where(df_flexiloansI['Lead last Disposition '] =='Post PD Hold',df_flexiloansI['Loan Amount'], "")
df_flexiloansI['PF Charges'] = ''
df_flexiloansI['Doc Charges'] = ''
df_flexiloansI['Insurance Charges'] = ''
df_flexiloansI['Net Disbursed Amount'] = ''
df_flexiloansI['Interest Rate'] = ''
df_flexiloansI['Interest Rate Type'] = ''
df_flexiloansI['Tenure'] = ''
df_flexiloansI['Repayment Frequency'] = ''
df_flexiloansI['Approved Date'] = ''
df_flexiloansI['Disbursed Date'] = ''
df_flexiloansI['Post Sanctioned Status'] = ''
df_flexiloansI['Rejected Reason'] = ''

In [20]:
df_flexiloansR = pd.read_excel(path+'\\FL\\FL.xlsx',sheet_name='Rejected',engine='openpyxl')

In [21]:
df_flexiloansR['Customer ID'] = df_flexiloansR['code']
df_flexiloansR['LAN'] = df_flexiloansR['application_no']
df_flexiloansR['Contact No.'] = df_flexiloansR['Mobile_no']
df_flexiloansR['Lender Partner '] = 'Flexi Loans'
df_flexiloansR['Merchant Name '] = ''
df_flexiloansR['Business Name '] = df_flexiloansR['business_name']
df_flexiloansR['Region'] = ''
df_flexiloansR['State'] = ''
df_flexiloansR['City'] = ''
df_flexiloansR['Final Lead Status'] = df_flexiloansR['s1']
df_flexiloansR['Lead Created Date'] = df_flexiloansR['Created']
df_flexiloansR['Lead last Disposition '] = df_flexiloansR['s3']
df_flexiloansR['Last disposition Date'] = ''
df_flexiloansR['Pendency'] = ''
df_flexiloansR['Monthly turn over of merchant'] = ''
df_flexiloansR['Loan Amount Requested'] = df_flexiloansR['Loan Amount']
df_flexiloansR['Sanctioned Amount'] = ''
df_flexiloansR['PF Charges'] = ''
df_flexiloansR['Doc Charges'] = ''
df_flexiloansR['Insurance Charges'] = ''
df_flexiloansR['Net Disbursed Amount'] = ''
df_flexiloansR['Interest Rate'] = ''
df_flexiloansR['Interest Rate Type'] = ''
df_flexiloansR['Tenure'] = ''
df_flexiloansR['Repayment Frequency'] = ''
df_flexiloansR['Approved Date'] = ''
df_flexiloansR['Disbursed Date'] = ''
df_flexiloansR['Post Sanctioned Status'] = ''
df_flexiloansR['Rejected Reason'] = np.where(df_flexiloansR['s1']=='Not approved',df_flexiloansR['s2']+" & " + df_flexiloansR['s3'],"")

In [22]:
df_LK_final = df_lendingkart[['Customer ID', 'LAN',
       'Contact No.', 'Lender Partner ', 'Merchant Name ', 'Business Name ',
       'Region', 'State', 'City', 'Final Lead Status', 'Lead Created Date',
       'Lead last Disposition ', 'Last disposition Date', 'Pendency',
       'Monthly turn over of merchant', 'Loan Amount Requested',
       'Sanctioned Amount', 'PF Charges', 'Doc Charges', 'Insurance Charges',
       'Net Disbursed Amount', 'Interest Rate', 'Interest Rate Type', 'Tenure',
       'Repayment Frequency', 'Approved Date', 'Disbursed Date',
       'Post Sanctioned Status', 'Rejected Reason']]

In [23]:
df_FLA = df_flexiloansA[['Customer ID', 'LAN',
       'Contact No.', 'Lender Partner ', 'Merchant Name ', 'Business Name ',
       'Region', 'State', 'City', 'Final Lead Status', 'Lead Created Date',
       'Lead last Disposition ', 'Last disposition Date', 'Pendency',
       'Monthly turn over of merchant', 'Loan Amount Requested',
       'Sanctioned Amount', 'PF Charges', 'Doc Charges', 'Insurance Charges',
       'Net Disbursed Amount', 'Interest Rate', 'Interest Rate Type', 'Tenure',
       'Repayment Frequency', 'Approved Date', 'Disbursed Date',
       'Post Sanctioned Status', 'Rejected Reason']]

In [24]:
df_FLR = df_flexiloansR[['Customer ID', 'LAN',
       'Contact No.', 'Lender Partner ', 'Merchant Name ', 'Business Name ',
       'Region', 'State', 'City', 'Final Lead Status', 'Lead Created Date',
       'Lead last Disposition ', 'Last disposition Date', 'Pendency',
       'Monthly turn over of merchant', 'Loan Amount Requested',
       'Sanctioned Amount', 'PF Charges', 'Doc Charges', 'Insurance Charges',
       'Net Disbursed Amount', 'Interest Rate', 'Interest Rate Type', 'Tenure',
       'Repayment Frequency', 'Approved Date', 'Disbursed Date',
       'Post Sanctioned Status', 'Rejected Reason']]

In [25]:
df_FLI = df_flexiloansI[['Customer ID', 'LAN',
       'Contact No.', 'Lender Partner ', 'Merchant Name ', 'Business Name ',
       'Region', 'State', 'City', 'Final Lead Status', 'Lead Created Date',
       'Lead last Disposition ', 'Last disposition Date', 'Pendency',
       'Monthly turn over of merchant', 'Loan Amount Requested',
       'Sanctioned Amount', 'PF Charges', 'Doc Charges', 'Insurance Charges',
       'Net Disbursed Amount', 'Interest Rate', 'Interest Rate Type', 'Tenure',
       'Repayment Frequency', 'Approved Date', 'Disbursed Date',
       'Post Sanctioned Status', 'Rejected Reason']]

In [26]:
df_FL_final = df_FLA.append(df_FLR).append(df_FLI)

In [27]:
df_FL_final.head()

,Customer ID,LAN,Contact No.,Lender Partner,Merchant Name,Business Name,Region,State,City,Final Lead Status,Lead Created Date,Lead last Disposition,Last disposition Date,Pendency,Monthly turn over of merchant,Loan Amount Requested,Sanctioned Amount,PF Charges,Doc Charges,Insurance Charges,Net Disbursed Amount,Interest Rate,Interest Rate Type,Tenure,Repayment Frequency,Approved Date,Disbursed Date,Post Sanctioned Status,Rejected Reason
0,65c60fcdgydn5,PEF-UTCAN-000-FEB24-00004,9793807225,Flexi Loans,,M/S LIBAS MAHAL,,,,Disbursed,2024-02-09,None,,,,500000,210000,4.13,7080,,186630.2,1.5,Flat,24,Months,2024-02-13 13:29:33,2024-02-13 00:00:00,,
1,65d78394b7z7f,PEF-UTGYA-000-FEB24-00011,8057367368,Flexi Loans,,KRISHNA SALES,,,,Disbursed,2024-02-22,None,,,,1000000,1000000,2.95,7080,,938243.0,1.3,Flat,30,Months,2024-02-24 22:51:05,2024-02-27 00:00:00,,
2,65d9d492bscg9,PEF-GUDAH-000-FEB24-00016,9727021890,Flexi Loans,,SIDDHI ELECTRONICS,,,,Disbursed,2024-02-24,None,,,,1000000,500000,2.95,5900,,479016.0,1.0,Flat,36,Months,2024-02-27 13:05:48,2024-02-29 00:00:00,,
3,65b63bbbfbalc,PEF-DESOU-000-JAN24-00012,9990876005,Flexi Loans,,AHIBIA COLLECTION,,,,Disbursed,2024-01-28,None,,,,2500000,1500000,2.36,5900,,1450450.0,1.5,Variable,36,Months,2024-02-09 20:14:20,2024-02-13 00:00:00,,
4,65c5fbcbhkyv5,PNF-UTIQB-000-FEB24-00001,9012912019,Flexi Loans,,AL LIMRA AIR CONDITIONER,,,,Disbursed,2024-02-09,None,,,,1000000,285000,2.36,5900,,270344.0,1.3,Flat,24,Months,2024-02-23 20:17:57,2024-03-08 00:00:00,,

In [28]:
df_FL_final['Contact No.'].nunique()

746

In [29]:
df_FL_final.shape

(884, 29)

In [30]:
df_FL_final['Lead Created Date']=df_FL_final['Lead Created Date'].astype('datetime64[ns]')

In [31]:
df_FL_final['Lead Created Date'].dtype

dtype('<M8[ns]')

In [32]:
df_LK_final['Lead Created Date']=df_LK_final['Lead Created Date'].astype('datetime64[ns]')

In [33]:
df_FL_final['Sanctioned Amount'].dtype

dtype('O')

In [34]:
df_LK_final['Lead Created Date'].dtype

dtype('<M8[ns]')

In [35]:
#pd.to_numeric(df_FL_final['Sanctioned Amount'], errors="ignore")
df_FL_final['Sanctioned Amount']=df_FL_final['Sanctioned Amount'].replace('',0).astype(float)
df_FL_final['Sanctioned Amount'].dtype

dtype('float64')

In [36]:
#df_FL_final = df_FL_final.sort_values(by=['Contact No.','Lead Created Date'],ascending=[False,False])

In [37]:
df_LK_final['Disbursed Date'].dtype
df_LK_final['Disbursed Date']=pd.to_datetime(df_LK_final['Disbursed Date'])
df_LK_final['Disbursed Date'].dtype
df_FL_final['Disbursed Date'].dtype
df_FL_final['Disbursed Date']=pd.to_datetime(df_FL_final['Disbursed Date'])
df_FL_final['Disbursed Date'].dtype

dtype('<M8[ns]')

In [38]:
df_LK_final['Sanctioned Amount'].dtype

dtype('float64')

In [39]:
#df_LK_final = df_LK_final.sort_values(by=['Contact No.','Lead Created Date'],ascending=[False,False])

In [40]:
df_FL_final = df_FL_final.sort_values(by=['Contact No.','Lead Created Date'],ascending=[True,True])

In [41]:
df_LK_final = df_LK_final.sort_values(by=['Contact No.','Lead Created Date'],ascending=[True,True])

In [42]:
T = str(((date.today()).strftime("%Y%m%d")))

In [43]:
df_Final = df_FL_final.append(df_LK_final)

In [44]:
#df_Final['Lead Created Date'] =pd.todatetime(df_Final['Lead Created Date'],format="%Y:%M:%D")

In [45]:
df_Final = df_Final.sort_values(by=['Contact No.','Lead Created Date'],ascending=[True,True])

In [46]:
#adding dicsionary to add one column (Reverse Mapping)
Mapping_dictionary ={'Agreement Signed' : 'Approved' , 'Agreement Stage' : 'Approved' , 'Application in Progress' : 'InComplete Appl' ,'Application Rejected': 'Reject', 'Application under Evaluation' : 'In Process' , 'Approved' : 'Approved' , 
'Closed': 'Reject' , 'Disbursed': 'Disbursed' , 'Fresh Lead': 'New Lead', 'Hot Lead': 'In Process',
 'Not approved':'Reject' ,'Qualified Lead': 'InComplete Appl' ,'Terms & Conditions Stage' : 'Approved'}

#df_Final['Final Status'] = df_Final['Final Lead Status'].map(Mapping_dictionary)

df_Final['Final Status'] = np.where(df_Final['Lead last Disposition ']== "Not Started", 'New Lead',df_Final['Final Lead Status'].map(Mapping_dictionary))
df_Final['Final Status'] = np.where(df_Final['Lead last Disposition ']== "Post PD Hold", 'Approved',df_Final['Final Lead Status'].map(Mapping_dictionary))
#df_Final['Sanctioned Amount']=df_Final['Sanctioned Amount'].astype(int)
df_Final['Approved Amount']=df_Final['Sanctioned Amount'].div(100000).round(3)

In [47]:
#df_Final['Count']=df_Final.groupby(['Contact No.','Lender Partner '])[['Contact No.']].count()

In [48]:
df_Final.head()

,Customer ID,LAN,Contact No.,Lender Partner,Merchant Name,Business Name,Region,State,City,Final Lead Status,Lead Created Date,Lead last Disposition,Last disposition Date,Pendency,Monthly turn over of merchant,Loan Amount Requested,Sanctioned Amount,PF Charges,Doc Charges,Insurance Charges,Net Disbursed Amount,Interest Rate,Interest Rate Type,Tenure,Repayment Frequency,Approved Date,Disbursed Date,Post Sanctioned Status,Rejected Reason,Final Status,Approved Amount
3182,35829771,LAI-121598084,6.001425e+09,LendingKart,mintu pathak,INNOVATION,,ASSAM,BAKSA,Terms & Conditions Stage,2024-02-02,Terms Created,23-03-2024,Terms Non-Moving,30 - 60 Lacs,1000000,973000.0,40017.4,,18238.0,NaN,1.06,Flat,36.0,,06-02-2024,NaT,Needs Better Terms,NaN,Approved,9.73
23,65ec2b00g706y,PEF-RAB.S-000-MAR24-00004,6.001567e+09,Flexi Loans,,YAKSHI MOBILE,,,,Disbursed,2024-03-09,None,,,,2000000,1375000.0,2.36,8850,,1331300.0,1.0,Flat,36,Months,2024-03-12 20:50:03,2024-03-16,,,Disbursed,13.75
1836,36149174,LAI-121811215,6.200634e+09,LendingKart,GULAM RABBANI,NaN,,NaN,NaN,Application Rejected,2024-02-16,Reject - Lead,16-02-2024,NaN,1 - 10 Crores,700000,NaN,NaN,,NaN,NaN,NaN,NaN,NaN,,NaN,NaT,NaN,Not Registered Business,Reject,NaN
2075,36265812,LAI-121887964,6.200751e+09,LendingKart,NILESH KUMAR,HB MOBILE,,JHARKHAND,JAMUA,Disbursed,2024-02-20,Disbursed,22-02-2024,Disbursed,1 - 10 Crores,250000,178000.0,12000.0,,4238.0,178000.0,1.5,Flat,24.0,,21-02-2024,2024-02-22,NaN,NaN,Disbursed,1.78
1092,35494560,LAI-121369391,6.201240e+09,LendingKart,Gurpreet Saini,NaN,,NaN,NaN,Application in Progress,2024-01-14,Application Details Incomplete,28-01-2024,NaN,1 - 10 Crores,1200000,NaN,NaN,,NaN,NaN,NaN,NaN,NaN,,NaN,NaT,NaN,NaN,InComplete Appl,NaN

In [49]:
df_Final.dtypes

Customer ID                              object
LAN                                      object
Contact No.                             float64
Lender Partner                           object
Merchant Name                            object
Business Name                            object
Region                                   object
State                                    object
City                                     object
Final Lead Status                        object
Lead Created Date                datetime64[ns]
Lead last Disposition                    object
Last disposition Date                    object
Pendency                                 object
Monthly turn over of merchant            object
Loan Amount Requested                     int64
Sanctioned Amount                       float64
PF Charges                               object
Doc Charges                              object
Insurance Charges                        object
Net Disbursed Amount                     object
Interest Rate                            object
Interest Rate Type                       object
Tenure                                   object
Repayment Frequency                      object
Approved Date                            object
Disbursed Date                   datetime64[ns]
Post Sanctioned Status                   object
Rejected Reason                          object
Final Status                             object
Approved Amount                         float64
dtype: object

In [50]:
df_Indifi= pd.read_csv(path+'\\Indifi\\applications.csv')

In [51]:
df_Indifi.head()

,request_id,id,name,phone,anchor_unique_id,anchor,city,location,applied_amount,state,lead_date,lead_time,application_date,application_time,sanction_amount,sanction_date,sanction_time,disbursed_amount,disbursed_date,disbursed_time,interest_rate,processing_fee,rejection_date,rejection_time,rejection_reason,utm_source,utm_campaign,utm_medium,is_renewed,business_nature,anchor_applicationid,application_completion_date,application_completion_time,is_womenled,fast_loan_link,rejection_code,dsa_agent_id
0,7703400,8ae4c34f-3647-45c0-b0d9-f8c31cfa765e,R-Ket's,7.719072e+09,{0},Pinelabs,Pune,Maharashtra,300000.0,Rejected,01-04-2024,12:39,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,01-04-2024,02:32,Duplicate Application,'---,'---,'---,True,Service,NaN,NaN,NaN,NaN,'-,dupe_application,NaN
1,7701895,e3079756-f8bf-40b8-bb61-4a882c89e595,R-Ket's,7.719072e+09,{0},Pinelabs,Pune,Maharashtra,300000.0,Rejected,01-04-2024,12:45,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,01-04-2024,02:25,Duplicate Application,'---,'---,'---,True,Service,NaN,NaN,NaN,NaN,'-,dupe_application,NaN
2,7690681,89c15a84-0ec0-4495-8ed2-f03070c651a0,SAI BOOK CENTER,7.028206e+09,NaN,Pinelabs,NaN,NaN,200000.0,Rejected,29-03-2024,10:09,29-03-2024,10:29,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,29-03-2024,10:11,Credit Risk Assessment,'---,'---,'---,False,NaN,NaN,NaN,NaN,NaN,'-,credit_reject,NaN
3,7690417,f7426188-0407-4da7-860f-a816742ceef3,SAI BOOK CENTER,9.766086e+09,NaN,Pinelabs,NaN,NaN,500000.0,Rejected,29-03-2024,08:51,29-03-2024,08:30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,29-03-2024,08:05,Credit Risk Assessment,'---,'---,'---,False,NaN,NaN,NaN,NaN,NaN,'-,credit_reject,NaN
4,7678581,32c9e8b9-0280-4199-8be1-54991b201342,I MOBILE,9.827304e+09,"{00,66040dbba38ab4942fb43721}",Pinelabs,Jabalpur,Madhya Pradesh,NaN,Incomplete,27-03-2024,06:15,27-03-2024,06:23,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,'---,'---,'---,False,Trading,NaN,NaN,NaN,NaN,'-,NaN,NaN

In [52]:
df_Indifi.columns

Index(['request_id', 'id', 'name', 'phone', 'anchor_unique_id', 'anchor',
       'city', 'location', 'applied_amount', 'state', 'lead_date', 'lead_time',
       'application_date', 'application_time', 'sanction_amount',
       'sanction_date', 'sanction_time', 'disbursed_amount', 'disbursed_date',
       'disbursed_time', 'interest_rate', 'processing_fee', 'rejection_date',
       'rejection_time', 'rejection_reason', 'utm_source', 'utm_campaign',
       'utm_medium', 'is_renewed', 'business_nature', 'anchor_applicationid',
       'application_completion_date', 'application_completion_time',
       'is_womenled', 'fast_loan_link', 'rejection_code', 'dsa_agent_id'],
      dtype='object')

In [53]:
df_Indifi.dtypes

request_id                       int64
id                              object
name                            object
phone                          float64
anchor_unique_id                object
anchor                          object
city                            object
location                        object
applied_amount                 float64
state                           object
lead_date                       object
lead_time                       object
application_date                object
application_time                object
sanction_amount                float64
sanction_date                   object
sanction_time                   object
disbursed_amount               float64
disbursed_date                  object
disbursed_time                  object
interest_rate                  float64
processing_fee                 float64
rejection_date                  object
rejection_time                  object
rejection_reason                object
utm_source                      object
utm_campaign                    object
utm_medium                      object
is_renewed                        bool
business_nature                 object
anchor_applicationid           float64
application_completion_date     object
application_completion_time     object
is_womenled                    float64
fast_loan_link                  object
rejection_code                  object
dsa_agent_id                   float64
dtype: object

In [54]:
df_Indifi[df_Indifi['disbursed_date'].notnull()].head(10)

,request_id,id,name,phone,anchor_unique_id,anchor,city,location,applied_amount,state,lead_date,lead_time,application_date,application_time,sanction_amount,sanction_date,sanction_time,disbursed_amount,disbursed_date,disbursed_time,interest_rate,processing_fee,rejection_date,rejection_time,rejection_reason,utm_source,utm_campaign,utm_medium,is_renewed,business_nature,anchor_applicationid,application_completion_date,application_completion_time,is_womenled,fast_loan_link,rejection_code,dsa_agent_id
9,7669163,49463f27-be7f-4991-a1f7-c61bb0238f97,MAHI SALES,9.574337e+09,NaN,Pinelabs,Panch Mahals,Gujarat,750000.0,Loan Active,26-03-2024,03:53,26-03-2024,03:27,761595.0,27-03-2024,01:34,761595.0,28-03-2024,07:10,24.0,29566.64,NaN,NaN,NaN,'---,'---,'---,False,Trading,NaN,26-03-2024,06:22,NaN,'-,NaN,NaN
25,7654668,4a5d7511-52a1-470f-85d8-f58177f060c9,The interior solutions,9.540331e+09,NaN,Pinelabs,Gurgaon,Haryana,1000000.0,Loan Active,22-03-2024,05:23,22-03-2024,05:23,1015460.0,26-03-2024,07:32,1015460.0,28-03-2024,08:13,23.0,51404.62,NaN,NaN,NaN,'---,'---,'---,False,Service,NaN,22-03-2024,05:43,NaN,'-,NaN,NaN
55,7613998,ecaeef87-589a-4577-b0e5-afa85dec8aa8,SRI VARI TRADERS,9.945986e+09,{00},Pinelabs,Bangalore,Karnataka,1000000.0,Loan Active,18-03-2024,06:37,18-03-2024,06:10,1015460.0,21-03-2024,02:47,1015460.0,27-03-2024,10:34,25.0,29956.07,NaN,NaN,NaN,'---,'---,'---,False,Retail,NaN,19-03-2024,06:45,NaN,'-,NaN,NaN
93,7571669,95890f41-905c-4c2c-afad-6b6ccad6bd7e,Mobile Campus and Electronic,7.088332e+09,{00},Pinelabs,Haridwar,Uttarakhand,1500000.0,Loan Active,12-03-2024,06:44,12-03-2024,06:44,246843.0,15-03-2024,04:58,246843.0,19-03-2024,02:12,31.0,8738.24,NaN,NaN,NaN,'---,'---,'---,False,Trading,NaN,13-03-2024,11:27,NaN,'-,NaN,NaN
138,7526160,db8719e8-7862-46c1-9290-5aa62a8b9a47,RIQUEZA ELECTRIC VEHICLES PRIVATE LIMITED,9.821448e+09,{00},Pinelabs,Thane,Maharashtra,160000.0,Loan Active,07-03-2024,04:58,07-03-2024,04:58,160000.0,16-03-2024,12:32,160000.0,27-03-2024,05:00,32.0,8477.12,NaN,NaN,NaN,'---,'---,'---,False,Trading,NaN,13-03-2024,10:18,NaN,'-,NaN,NaN
167,7504581,0cc91401-7785-42cc-b4f2-e22b2de4c6ef,SK TRADING,9.506576e+09,{00},Pinelabs,Gorakhpur,Uttar Pradesh,1500000.0,Loan Active,05-03-2024,06:52,05-03-2024,06:18,323180.0,13-03-2024,04:13,323180.0,16-03-2024,04:41,33.0,11440.57,NaN,NaN,NaN,'---,'---,'---,False,Retail,NaN,13-03-2024,03:38,NaN,'-,NaN,NaN
232,7399605,6820943a-fb68-4c49-839e-30e442d143a7,MEDOC CLOTHINGS PRIVATE LIMITED,9.574823e+09,{00},Pinelabs,Valsad,Gujarat,145000.0,Loan Active,26-02-2024,03:57,26-02-2024,04:16,147241.0,01-03-2024,01:22,147241.0,14-03-2024,12:28,34.0,5716.19,NaN,NaN,NaN,'---,'---,'---,False,Retail,NaN,28-02-2024,10:52,NaN,'-,NaN,NaN
245,7380049,65d7e721-75ad-4e46-9169-3a672edb418a,VANI OILS,9.951775e+09,{00},Pinelabs,Nellore,Andhra Pradesh,983000.0,Loan Active,24-02-2024,12:12,24-02-2024,12:24,998197.0,29-02-2024,01:01,998197.0,29-02-2024,05:00,33.0,50530.73,NaN,NaN,NaN,'---,'---,'---,False,Trading,NaN,28-02-2024,05:00,NaN,'-,NaN,NaN
250,7372956,81eb0e92-6732-4d32-a6e5-4f7ed3b42bb3,Guru Kripa Electronics,9.896798e+09,{00},Pinelabs,Sonipat,Haryana,444000.0,Loan Active,23-02-2024,03:11,23-02-2024,03:30,450864.0,24-02-2024,10:03,450864.0,27-02-2024,02:25,32.0,22823.64,NaN,NaN,NaN,'---,'---,'---,False,Trading,NaN,23-02-2024,04:37,NaN,'-,NaN,NaN
270,7361569,98da87e2-8736-4ca4-8ee6-47469a4b84ab,LIONS KARATE CLUB,9.099752e+09,"{00,65339cd3fdb2e2a2ec9fd556}",Pinelabs,Jamnagar,Gujarat,431000.0,Loan Active,22-02-2024,02:36,22-02-2024,02:36,334277.0,23-02-2024,11:41,334277.0,26-02-2024,01:37,32.0,11833.41,NaN,NaN,NaN,'---,'---,'---,False,Service,NaN,23-02-2024,10:23,NaN,'-,NaN,NaN

In [55]:
Mapping_dictionary_Indifi ={'Documentation Pending' : 'Approved' , 'Incomplete' : 'InComplete Appl' , 'Loan Active' : 'Disbursed' ,'Offer Acceptance Pending': 'Approved', 'Processing For Offer' : 'In Process' , 'Rejected' : 'Reject' , 
'Withdrawn': 'Reject','Ready To Disburse':'Approved','Under Review For Offer':'In Process'}

In [56]:
df_Indifi['Customer ID'] = df_Indifi['anchor_unique_id']
df_Indifi['LAN'] = df_Indifi['request_id']
df_Indifi['Contact No.'] = df_Indifi['phone']
df_Indifi['Lender Partner '] = 'Indifi'
df_Indifi['Merchant Name '] = ''
df_Indifi['Business Name '] = df_Indifi['name']
df_Indifi['Region'] = ''
df_Indifi['State'] = df_Indifi['location']
df_Indifi['City'] = df_Indifi['city']
df_Indifi['Final Lead Status'] =df_Indifi['state']
df_Indifi['Lead Created Date'] = df_Indifi['lead_date']
df_Indifi['Lead last Disposition '] =df_Indifi['state']
df_Indifi['Last disposition Date'] =df_Indifi['application_completion_date']
df_Indifi['Pendency'] =''
df_Indifi['Monthly turn over of merchant'] = ''
df_Indifi['Loan Amount Requested'] = df_Indifi['applied_amount']
df_Indifi['Sanctioned Amount'] =np.where(df_Indifi['Lead last Disposition '] =='Offer Acceptance Pending',df_Indifi['Loan Amount Requested'],df_Indifi['sanction_amount'])
df_Indifi['PF Charges'] =''
df_Indifi['Doc Charges'] = ''
df_Indifi['Insurance Charges'] = ''
df_Indifi['Net Disbursed Amount'] =df_Indifi['disbursed_amount']
df_Indifi['Interest Rate'] = df_Indifi['interest_rate']
df_Indifi['Interest Rate Type'] = ''
df_Indifi['Tenure'] =''
df_Indifi['Repayment Frequency'] = ''
df_Indifi['Approved Date'] =df_Indifi['sanction_date']
df_Indifi['Disbursed Date'] =df_Indifi['disbursed_date']
df_Indifi['Post Sanctioned Status'] = ''
df_Indifi['Rejected Reason'] =df_Indifi['rejection_reason']
df_Indifi['Final Status']=df_Indifi['state'].map(Mapping_dictionary_Indifi)
df_Indifi['Sanctioned Amount'] = pd.to_numeric(df_Indifi['Sanctioned Amount'], errors='coerce')
df_Indifi['Approved Amount']=df_Indifi['Sanctioned Amount'].div(100000).round(3)
df_Indifi['lead_time']=df_Indifi['lead_time']

In [57]:
df_Indifi_final=df_Indifi[['Customer ID', 'LAN',
       'Contact No.', 'Lender Partner ', 'Merchant Name ', 'Business Name ',
       'Region', 'State', 'City', 'Final Lead Status', 'Lead Created Date',
       'Lead last Disposition ', 'Last disposition Date', 'Pendency',
       'Monthly turn over of merchant', 'Loan Amount Requested',
       'Sanctioned Amount', 'PF Charges', 'Doc Charges', 'Insurance Charges',
       'Net Disbursed Amount', 'Interest Rate', 'Interest Rate Type', 'Tenure',
       'Repayment Frequency', 'Approved Date', 'Disbursed Date',
       'Post Sanctioned Status', 'Rejected Reason','Final Status','Approved Amount','lead_time']]

In [58]:
df_Indifi_final.dtypes

Customer ID                       object
LAN                                int64
Contact No.                      float64
Lender Partner                    object
Merchant Name                     object
Business Name                     object
Region                            object
State                             object
City                              object
Final Lead Status                 object
Lead Created Date                 object
Lead last Disposition             object
Last disposition Date             object
Pendency                          object
Monthly turn over of merchant     object
Loan Amount Requested            float64
Sanctioned Amount                float64
PF Charges                        object
Doc Charges                       object
Insurance Charges                 object
Net Disbursed Amount             float64
Interest Rate                    float64
Interest Rate Type                object
Tenure                            object
Repayment Frequency               object
Approved Date                     object
Disbursed Date                    object
Post Sanctioned Status            object
Rejected Reason                   object
Final Status                      object
Approved Amount                  float64
lead_time                         object
dtype: object

In [59]:
#df_Indifi_final['Disbursed Date']=df_Indifi_final['Disbursed Date'].astype('datetime64[ns]')

In [60]:
df_Indifi_final['Disbursed Date'] = pd.to_datetime(df_Indifi_final['Disbursed Date'].str.slice(6,10)+'-'+df_Indifi_final['Disbursed Date'].str.slice(3,5)+'-'+df_Indifi_final['Disbursed Date'].str.slice(0,2))

In [61]:
df_Indifi_final['Disbursed Date']=pd.to_datetime(df_Indifi_final['Disbursed Date'], errors='coerce')

In [62]:
df_Indifi_final['Lead Created Date'] = pd.to_datetime(df_Indifi_final['Lead Created Date'].str.slice(6,10)+'-'+df_Indifi_final['Lead Created Date'].str.slice(3,5)+'-'+df_Indifi_final['Lead Created Date'].str.slice(0,2))

In [63]:
df_Indifi_final['Lead Created Date']=pd.to_datetime(df_Indifi_final['Lead Created Date'], errors='coerce')

In [64]:
df_Indifi_final['Loan Amount Requested']=df_Indifi_final['Loan Amount Requested'].astype('Int64',errors='ignore')

In [65]:
df_Indifi_final['Net Disbursed Amount']=df_Indifi_final['Net Disbursed Amount'].astype(object)

In [66]:
df_Indifi_final['Interest Rate']=df_Indifi_final['Interest Rate'].astype(object)

In [67]:
df_Indifi_final.dtypes

Customer ID                              object
LAN                                       int64
Contact No.                             float64
Lender Partner                           object
Merchant Name                            object
Business Name                            object
Region                                   object
State                                    object
City                                     object
Final Lead Status                        object
Lead Created Date                datetime64[ns]
Lead last Disposition                    object
Last disposition Date                    object
Pendency                                 object
Monthly turn over of merchant            object
Loan Amount Requested                     Int64
Sanctioned Amount                       float64
PF Charges                               object
Doc Charges                              object
Insurance Charges                        object
Net Disbursed Amount                     object
Interest Rate                            object
Interest Rate Type                       object
Tenure                                   object
Repayment Frequency                      object
Approved Date                            object
Disbursed Date                   datetime64[ns]
Post Sanctioned Status                   object
Rejected Reason                          object
Final Status                             object
Approved Amount                         float64
lead_time                                object
dtype: object

In [68]:
df_Indifi_final = df_Indifi_final.sort_values(by=['Contact No.','Lead Created Date','lead_time'],ascending=[True,True,True])

In [69]:
df_Final = df_Final.append(df_Indifi_final)

In [70]:
path = os.getcwd()

In [71]:
path

'C:\\Users\\Tithi Hunka\\OneDrive - Pine Labs Private Limited\\TermLoans Code_Dummy'

In [72]:
df_Final.to_excel(path+'\\Output\\excel_final.xlsx',index=False)

In [73]:
df_Final.to_csv(path+'\\Output\\TermLoansConsolidated_'+ T+'.csv',index=False)

In [74]:
wb1= openpyxl.load_workbook("C:\\Users\\Tithi Hunka\\OneDrive - Pine Labs Private Limited\Term Loan Case Tracker (Inside Sales)_ (2).xlsx")#form opening

In [75]:
wb2= openpyxl.load_workbook("C:\\Users\\Tithi Hunka\\OneDrive - Pine Labs Private Limited\\TermLoans Code_Dummy\\Output\\excel_final.xlsx")#consolidated opening

In [76]:
#sheet = wb1['Form1']
#sheet['Q2'] = 'Hi'
#wb1.save('C:\\Users\\Tithi Hunka\\OneDrive - Pine Labs Private Limited\Pine Labs Form.xlsx')

In [77]:
#for i in range(2,wb1["Form1"].max_row+1):
    #for j in range(2,wb2["Sheet1"].max_row+1):
         #if(int((wb1["Form1"].cell(row=i,column=10).value)== wb2["Sheet1"].cell(row=j,column=3).value) and ((wb1["Form1"].cell(row=i,column=15).value==wb2["Sheet1"].cell(row=j,column=4).value))): 
            #wb1["Form1"].cell(row=i,column=25).value=wb2["Sheet1"].cell(row=j,column=30).value
            #wb1["Form1"].cell(row=i,column=25).value="Matched"
            #print(i)
            #print(j)
            #print(wb1["Form1"].cell(row=i,column=8).value)
            #print(wb2["Sheet1"].cell(row=j,column=3).value)
            #print(wb1["Form1"].cell(row=i,column=16).value)
            #print(wb2["Sheet1"].cell(row=j,column=4).value)
            #print(wb2["Sheet1"].cell(row=i,column=30).value)
            #print(wb1["Form1"].cell(row=i,column=17).value)
         #else:
            #wb1["Form1"].cell(row=i,column=25).value=wb1["Form1"].cell(row=i,column=25).value
            #wb1["Form1"].cell(row=i,column=25).value="No"
            #continue

In [78]:
for i in range(2,wb1["Form1"].max_row+1):
    for j in range(2,wb2["Sheet1"].max_row+1):
        #wb1["Form1"].cell(row=i,column=8).value=wb1["Form1"].cell(row=i,column=8).value
        if((wb1["Form1"].cell(row=i,column=8).value== wb2["Sheet1"].cell(row=j,column=3).value) and ((wb1["Form1"].cell(row=i,column=15).value==wb2["Sheet1"].cell(row=j,column=4).value)) and (wb1["Form1"].cell(row=i,column=16).value=="Duplicate")):
            wb1["Form1"].cell(row=i,column=16).value=wb1["Form1"].cell(row=i,column=16).value
            wb1["Form1"].cell(row=i,column=17).value=wb1["Form1"].cell(row=i,column=17).value
            wb1["Form1"].cell(row=i,column=18).value=wb1["Form1"].cell(row=i,column=18).value
            wb1["Form1"].cell(row=i,column=19).value=wb1["Form1"].cell(row=i,column=19).value
            wb1["Form1"].cell(row=i,column=20).value=wb1["Form1"].cell(row=i,column=20).value
            wb1["Form1"].cell(row=i,column=22).value=wb1["Form1"].cell(row=i,column=22).value
            #wb1["Form1"].cell(row=i,column=27).value="No"
            continue
        elif(wb1["Form1"].cell(row=i,column=16).value=="Duplicate"):
            wb1["Form1"].cell(row=i,column=16).value=wb1["Form1"].cell(row=i,column=16).value
            wb1["Form1"].cell(row=i,column=17).value=wb1["Form1"].cell(row=i,column=17).value
            wb1["Form1"].cell(row=i,column=18).value=wb1["Form1"].cell(row=i,column=18).value
            wb1["Form1"].cell(row=i,column=19).value=wb1["Form1"].cell(row=i,column=19).value
            wb1["Form1"].cell(row=i,column=20).value=wb1["Form1"].cell(row=i,column=20).value
            wb1["Form1"].cell(row=i,column=22).value=wb1["Form1"].cell(row=i,column=22).value
            continue
        elif(int((wb1["Form1"].cell(row=i,column=8).value)== wb2["Sheet1"].cell(row=j,column=3).value) and ((wb1["Form1"].cell(row=i,column=15).value==wb2["Sheet1"].cell(row=j,column=4).value))): 
            wb1["Form1"].cell(row=i,column=16).value=wb2["Sheet1"].cell(row=j,column=30).value
            wb1["Form1"].cell(row=i,column=17).value=wb2["Sheet1"].cell(row=j,column=31).value
            wb1["Form1"].cell(row=i,column=18).value=wb2["Sheet1"].cell(row=j,column=27).value
            wb1["Form1"].cell(row=i,column=19).value=wb2["Sheet1"].cell(row=j,column=12).value
            wb1["Form1"].cell(row=i,column=20).value=wb2["Sheet1"].cell(row=j,column=29).value
            wb1["Form1"].cell(row=i,column=22).value=wb2["Sheet1"].cell(row=j,column=14).value
            #wb1["Form1"].cell(row=i,column=27).value="Matched"
            continue
        else:
            wb1["Form1"].cell(row=i,column=16).value=wb1["Form1"].cell(row=i,column=16).value
            wb1["Form1"].cell(row=i,column=17).value=wb1["Form1"].cell(row=i,column=17).value
            wb1["Form1"].cell(row=i,column=18).value=wb1["Form1"].cell(row=i,column=18).value
            wb1["Form1"].cell(row=i,column=19).value=wb1["Form1"].cell(row=i,column=19).value
            wb1["Form1"].cell(row=i,column=20).value=wb1["Form1"].cell(row=i,column=20).value
            wb1["Form1"].cell(row=i,column=22).value=wb1["Form1"].cell(row=i,column=22).value
            #wb1["Form1"].cell(row=i,column=25).value="No"
            continue

In [79]:
wb1.save('C:\\Users\\Tithi Hunka\\OneDrive - Pine Labs Private Limited\\Term Loan Case Tracker (Inside Sales)_ (2).xlsx')

In [80]:
wb2.save('C:\\Users\\Tithi Hunka\\OneDrive - Pine Labs Private Limited\\TermLoans Code_Dummy\\Output\\excel_final.xlsx')